// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // DIRECT_DATABASE_URL isn't wired as shadowDatabaseUrl here because it
    // currently points at the same (non-pooled) Neon endpoint as
    // DATABASE_URL — Prisma Migrate rejects a shadow DB identical to the
    // main one. Once DATABASE_URL switches to a pooled connection string,
    // set shadowDatabaseUrl: process.env["DIRECT_DATABASE_URL"] here so
    // migrations diff against the direct connection instead of the pooler.
  },
});
